[project]
name = "min-demo"
version = "0.1.0"
dependencies = [
  "flask==2.3.3",
  "flask-restx==1.1.0",
  "flask_cors",
  "pymongo",
  "werkzeug==3.0.6",
  "python-dotenv==1.1.1",
  "certifi",
  "PyJWT==2.9.0",
]
requires-python = ">=3.8"
authors = [
  {name = "Bryant Chong", email = "bsc6136@nyu.edu"},
  {name = "Emily Wei", email = "ew2482@nyu.edu"},
  {name = "Maksym Yemelianenko", email = "my2658@nyu.edu"},
  {name = "George Sirichartchai", email = "gs3802@nyu.edu"},
]
readme = "README.md"